cemeteries/urls.py
from django.conf.urls import patterns, include, url
from .views import MainView, CemeteryListView, CemeteryDetailView, MarkerListView,MarkerDetailView, WWDCView,WWDCMapView
from .views import PersonListView, PersonDetailView,AboutView, SymbologyView, PeopleView, MarkerMapView,PersonMapView, SymbolMapView, IndividualMarkerMapView, IndividualPersonMapView
from .models import Cemetery, Marker, Person, Symbology
#from django.contrib.auth.decorators import login_required



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fuse2014.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', MainView.as_view(), name='main'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^cemeteries/$', CemeteryListView.as_view(model=Cemetery), name='cem_lview'),
    url(r'^cemeteries/(?P<pk>\d+)/$', CemeteryDetailView.as_view(), name='cem_dview'),
    url(r'^marker/$', MarkerListView.as_view(model=Marker), name='marker_lview'),
    url(r'^marker/(?P<pk>\d+)/$', MarkerDetailView.as_view(), name='marker_dview'),
    url(r'^person/$', PersonListView.as_view(model=Person), name='person_lview'),
    url(r'^person/(?P<pk>\d+)/$', PersonDetailView.as_view(), name='person_dview'),
    url(r'^people_search/$', PeopleView.as_view(), name='people_view'),
    url(r'^symbology/$', SymbologyView.as_view(model=Symbology), name='symbology'),
    url(r'^map_marker/$', MarkerMapView.as_view(), name='markermap'),
    url(r'^wwdc/$', WWDCView.as_view(), name='WWDC_view'),
    url(r'^map_person/$', PersonMapView.as_view(), name='personmap'),
    url(r'^map_wwdc/$', WWDCMapView.as_view(), name='WWDC_map'),
    url(r'^symbolmap/(?P<pk>\d+)/$', SymbolMapView.as_view(), name='symbolmap'),
    url(r'^markermap/(?P<pk>\d+)/$', IndividualMarkerMapView.as_view(), name='markermap'),
    url(r'^personmap/(?P<pk>\d+)/$', IndividualPersonMapView.as_view(), name='personmap'),
)

fuse2014/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.http import HttpResponse
from fuse2014.sitemaps import MainSitemap
from cemeteries.models import Person, Cemetery

sitemaps = {
    'mainpage': MainSitemap,
    'people': GenericSitemap({'queryset': Person.objects.all(), }, changefreq='monthly', priority=0.6),
    'cemeteries': GenericSitemap({'queryset': Cemetery.objects.all(), }, changefreq='monthly', priority=0.6),
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fuse2014.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cemeteries.urls', namespace='cemeteries')),
    url(r'^api/v1/', include('cemeteries.api_urls', namespace='cemeteries_api')),
    url(r'^search/', include('haystack.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^sitemap\.xml$',
        'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /api/", content_type="text/plain"))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cemeteries/models.py
from django.contrib.gis.db import models
from django_date_extensions.fields import ApproximateDateField


class Cemetery(models.Model):
    """ Cemetery model.

    Represents a cemetery.

    """
    name = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return "{} Cemetery".format(self.name)

    def get_absolute_url(self):
        return "/cemeteries/{}".format(self.pk)


class Marker(models.Model):
    """ Marker Model.

    Represents a cemetery marker (gravestone).

    """
    cemetery = models.ForeignKey(Cemetery)
    markerid = models.IntegerField(primary_key=True)
    condition = models.CharField(max_length=15)
    readable = models.BooleanField(default=None)
    epitaph = models.CharField(max_length=240)
    family_name = models.CharField(max_length=40)
    point = models.PointField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return "Markerid: {} - {}".format(self.markerid, self.cemetery)

    def get_absolute_url(self):
        return "/marker/{}".format(self.markerid)


class Person(models.Model):
    """ Person Model.

    Represents a person interred at a cemetery and connects them to their Marker.

    """

    markerid = models.ForeignKey(Marker)
    full_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=7)
    veteran = models.CharField(max_length=7)
    b_year = models.CharField(max_length=4)
    d_year = models.CharField(max_length=4)
    a_birth = ApproximateDateField(null=True)
    a_death = ApproximateDateField(null=True)
    epitaph = models.TextField()
    footstone = models.BooleanField(default=None)
    footstoneI = models.TextField()
    point = models.PointField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return "FullName : {0}, {1} Born: {2} Died: {3}".format(self.full_name, self.markerid, self.a_birth, self.a_death)

    def get_absolute_url(self):
        return "/person/{}".format(self.pk)


class MarkerImage(models.Model):
    """ MarkerImage Model

    Represents an image of a marker.

    """
    markerid = models.ForeignKey(Marker)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return "{}".format(self.markerid)


class Symbology(models.Model):
    """ Symbology Model

    """

    symbology = models.CharField(max_length=40)
    markers = models.ManyToManyField(Marker, blank=True)

    def __str__(self):
        return "{0}".format(self.symbology)


class WWDC(models.Model):
    """ World War Drafting Cards FileField

    Represents a PDF file of the card.

    """
    person = models.ForeignKey(Person)
    pdf = models.FileField(upload_to='draft_cards/')

    def __str__(self):
        return "{0}".format(self.person.full_name)

cemeteries/views.py
import datetime
from django.views import generic
from .models import Cemetery, Marker, Person, Symbology, MarkerImage, WWDC
from django.db.models import Q


def get_rel_referer(referer):
    back = "/" + "/".join(referer.split('/')[3:])
    return back


class MainView(generic.TemplateView):
    template_name = "cemeteries/mainpage.html"


class CemeteryListView(generic.ListView):
    model = Cemetery
    template_name = "cemeteries/cemeteries_simple.html"


class CemeteryDetailView(generic.DetailView):
    model = Cemetery
    template_name = "cemeteries/cemeteries_detail.html"


class MarkerListView(generic.ListView):
    model = Marker
    template_name = "cemeteries/markers_simple.html"


class MarkerDetailView(generic.TemplateView):
    template_name = "cemeteries/markers_detail.html"

    def get_context_data(self, **kwargs):
        """ Resize image.

        Resizes an to specified height while keeping the images aspect ratio. Used in the Marker Detail template if image
        exists.
        """
        context = super(MarkerDetailView, self).get_context_data(**kwargs)
        image = MarkerImage.objects.filter(markerid=kwargs['pk']).first()
        if image is not None:
            h_ratio = image.image.height / 800.0
            w_ratio = image.image.width / 700.0
            image.height = image.image.height / max(h_ratio, w_ratio)
            image.width = image.image.width / max(h_ratio, w_ratio)
            context['image'] = image
        marker = Marker.objects.filter(markerid=kwargs['pk']).first()
        people = Person.objects.filter(markerid=kwargs['pk'])
        context['marker'] = marker
        context['people'] = people
        refer = self.request.META.get('HTTP_REFERER')
        if refer is not None:
            context['back'] = get_rel_referer(refer)
        return context


class PersonListView(generic.ListView):
    model = Person
    template_name = "cemeteries/person_simple.html"


class PersonDetailView(generic.TemplateView):
    template_name = "cemeteries/person_detail.html"

    def get_context_data(self, **kwargs):
        """ Resize image.

        Resizes an to specified height while keeping the images aspect ratio. Used in the Person Detail template if image
        exists.
        """
        context = super(PersonDetailView, self).get_context_data(**kwargs)
        person = Person.objects.filter(pk=kwargs['pk']).first()
        image = MarkerImage.objects.filter(markerid=person.markerid.pk).first()
        if image is not None:
            h_ratio = image.image.height / 800.0
            w_ratio = image.image.width / 700.0
            image.height = image.image.height / max(h_ratio, w_ratio)
            image.width = image.image.width / max(h_ratio, w_ratio)
            context['image'] = image
        refer = self.request.META.get('HTTP_REFERER')
        if refer is not None:
            context['back'] = get_rel_referer(refer)
        context['person'] = person
        card = WWDC.objects.filter(person=person).first()
        context['wwdc'] = card
        return context


class AboutView(generic.TemplateView):
    template_name = "cemeteries/about.html"


class PeopleView(generic.TemplateView):
    template_name = "cemeteries/people_view.html"


    def get_context_data(self, **kwargs):
        context = super(PeopleView, self).get_context_data(**kwargs)
        groups = [['A', 'B ', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I'], ['J', 'K', 'L'],
                  ['M', 'N', 'O'], ['P', 'Q', 'R'], ['S', 'T', 'U'], ['V', 'W', 'X'],
                  ['Y', 'Z']]
        data = {}

        def group_people(letters):
            """ Using letters to locate matching letters in the database.

            The function group_people takes a list of letters as parameters and runs a query on the database. The the
            data is collected in a list and returned to a dictionary to be passed into the template.

            """
            key = " ".join(letters)
            qs = [Q(last_name__istartswith=letter) for letter in letters]
            final_q = None
            for q in qs:
                final_q = final_q | q if final_q else q
            p = Person.objects.filter(final_q)
            data[key] = p
        for g in groups:
            group_people(g)
        data = list(data.items())
        data.sort()
        context['groups'] = data
        return context


class SymbologyView(generic.ListView):
    model = Symbology
    template_name = "cemeteries/symbology.html"


class MarkerMapView(generic.TemplateView):
    template_name = "cemeteries/marker_map.html"


class PersonMapView(generic.TemplateView):
    template_name= "cemeteries/person_map.html"


class SymbolMapView(generic.TemplateView):
    template_name = "cemeteries/symbol_map.html"

    def get_context_data(self, **kwargs):
        context = super(SymbolMapView, self).get_context_data(**kwargs)
        symbol = Symbology.objects.filter(pk=kwargs['pk']).first()
        context['markers'] = "/api/v1/markers?markerid=" + ",".join([str(marker.markerid) for marker in symbol.markers.all()])
        context['symbol'] = symbol.symbology
        return context

class IndividualMarkerMapView(generic.TemplateView):
    template_name = "cemeteries/symbol_map.html"

    def get_context_data(self, **kwargs):
        context = super(IndividualMarkerMapView, self).get_context_data(**kwargs)
        marker = Marker.objects.filter(pk=kwargs['pk']).first()
        context['markers'] = "/api/v1/markers?markerid=" + "{}".format(marker.markerid)
        return context


class IndividualPersonMapView(generic.TemplateView):
    template_name = "cemeteries/individual_person_map.html"

    def get_context_data(self, **kwargs):
        context = super(IndividualPersonMapView, self).get_context_data(**kwargs)
        person = Person.objects.filter(pk=kwargs['pk']).first()
        context['people'] = "/api/v1/people?id=" + "{}".format(person.pk)
        return context


class WWDCView(generic.TemplateView):
    template_name = "cemeteries/wwdc.html"

    def get_context_data(self, **kwargs):
        context = super(WWDCView, self).get_context_data(**kwargs)

        def get_eligible(draft, registrations):
            eligible = Person.objects.filter(gender='Male')
            eligible = eligible.exclude(a_birth__gt=draft[0].isoformat().split('T')[0])
            eligible = eligible.exclude(a_birth__lt=draft[1].isoformat().split('T')[0])
            eligible = eligible.exclude(a_death__lt=draft[2].isoformat().split('T')[0])
            for registration in registrations:
                eligible = eligible.exclude(id__in=registration.values('pk'))
            for registrant in eligible:
                card = WWDC.objects.filter(person=registrant)
                registrant.wwdc = card.first()
            return eligible

        first_registration = (datetime.datetime(1896, 6, 5), datetime.datetime(1886, 6, 5), datetime.datetime(1917, 6, 5))
        second_registration = (datetime.datetime(1897, 6, 6), datetime.datetime(1896, 6, 6), datetime.datetime(1918, 6, 5))
        supplemental_registration = (datetime.datetime(1897, 8, 24), datetime.datetime(1897, 6, 6), datetime.datetime(1918, 6, 6))
        third_registration = (datetime.datetime(1900, 9, 12), datetime.datetime(1873, 9, 12), datetime.datetime(1918, 9, 12))
        registrations = [first_registration, second_registration, supplemental_registration, third_registration]
        registration_data = []

        for registration in registrations:
            registration_data.append(get_eligible(registration, registration_data))

        context['registrations'] = registration_data
        return context


class WWDCMapView(generic.TemplateView):
    template_name = "cemeteries/WWDC_map.html"

    def get_context_data(self, **kwargs):
        context = super(WWDCMapView, self).get_context_data(**kwargs)
        people = [str(card.person.pk) for card in WWDC.objects.all()]
        context['people'] = "/api/v1/people?id=" + ",".join(people)
        return context

cemeteries/templates/cemeteries/about.html
{% extends 'base.html' %}

{% block title %}About theyburied.us{% endblock %}


{% block content %}
  <h1>About theyburied.us</h1>
  <p style="font-size:20px">Our primary goal is to digitally preserve rural cemeteries in a way that includes images of each grave marker and an interactive map featuring a high resolution aerial photo of the cemetery site.  Our site also provides the ability to search and explore marker data such as names, birth and death dates.</p>
    <p style="font-size:20px">In addition to digital preservation we want to create a resource for cemeteries’ communities to explore their past.  We intend to connect the cemetery data we preserve to historic records such as <a href="{% url 'cemeteries:WWDC_view' %}">World War I draft cards</a> and other datasets. This site will also be a benefit to those doing genealogy or other types of research.</p>
{% endblock %}

cemeteries/templates/cemeteries/cemeteries_detail.html
{% extends 'base.html' %}

{% block title %}Cemeteries{% endblock %}


{% block content %}
  <font size="5" font face="Comic Sans MS">
    <h1>{{ object.name }}</h1>
    <p>{{ object.description }}</p>
    <a href="{% url 'cemeteries:cem_lview' %}">Return to List Of Cemeteries </a>
  </font>
{% endblock %}

cemeteries/templates/cemeteries/cemeteries_simple.html
{% extends 'base.html' %}

{% block title %}Cemeteries{% endblock %}
{% block content %}
    <font size="5" font face="Comic Sans MS">
    <h1><b>List of Cemeteries</b></h1>
  <ul>
    {% for cemetery in object_list %}
      <li><a href="{% url 'cemeteries:cem_dview' cemetery.pk %}">{{ cemetery.name|capfirst }}</a></li>
    {% endfor %}
  </ul>
  </font>
{% endblock %}

cemeteries/templates/cemeteries/individual_person_map.html
{% extends 'base.html' %}
{% block title %}Symbology Map{% endblock %}
{% block morehead %}
<script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.css' rel='stylesheet' />
{% endblock %}

{% block content %}
<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:52px; right:10px; left:0; bottom:0; width:100%; }
</style>

  <div id='map'></div>


{% endblock %}

{% block scriptspace %}
<script>

    var ouricon = {
            radius: 6,
            fillColor: "#DF0101",
            color: "#610B0B",
            weight: 1,
            opacity: 1,
            fillOpacity: 0.7
    };

    var map =  L.mapbox.map('map', 'zmiller1.icc1cno8');
    map.fitBounds([
    [34.345, -83.71],
    [34.34, -83.690]
    ]);
    map.setMaxBounds([
    [34.345, -83.71],
    [34.34, -83.690]
    ]);


    $.getJSON('{{ people }}', function (data) {
      L.geoJson(data, {pointToLayer: function (feature, latlng) {
            return L.circleMarker(latlng, ouricon);
        },
        onEachFeature: function (feature, layer) {
            (function(layer, properties) {
                layer.on("click", function (e) {



    var popup = L.popup()
         .setLatLng(e.latlng)
         .setContent('<a href="/person/' + feature.id + '">' + properties.full_name + '</a>')
         .openOn(map);
                });

                })(layer, feature.properties);
        },
        style: ouricon}).addTo(map);


    });

</script>
{% endblock %}

cemeteries/templates/cemeteries/mainpage.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}theyburied.us{% endblock %}

{% block morehead %}
  <meta name="google-site-verification" content="zO6kWKQT-oGe_TtBNbbqdO784se-dINAhgVOhm9WwBA" />
{% endblock %}



{% block content %}
  <!-- http://parkhurstdesign.com/improved-carousels-twitter-bootstrap/ to adjust image size before displaying-->
  <!-- Carousel ================================================== -->
  <section id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <figure class="item active">
        <img src="{% static 'cemeteries/images/carousel/Blue.jpg' %}">
        <figcaption class="carousel-caption">
          <h1>Visit Cemeteries</h1>
          <font size="5"><p>View Cemeteries Using a High Resolution Interactive Map</p></font>

          <p><a class="btn btn-lg btn-primary" href="{% url 'cemeteries:markermap' %}" role="button">Start Viewing Cemeteries</a></p>
        </figcaption>
      </figure>
      <figure class="item">
        <img src="{% static 'cemeteries/images/carousel/TBlue.jpg' %}" alt="Wage War">
        <figcaption class="carousel-caption">
          <h1>Search Symbology</h1>
          <font size="5"><p>Explore Grave Marker Symbology</p></font>

          <p><a class="btn btn-lg btn-primary" href="{% url 'cemeteries:symbology' %}" role="button">Examine Symbology</a></p>
        </figcaption>
      </figure>
      <figure class="item">
        <img src="{% static 'cemeteries/images/carousel/Green.jpg' %}" alt="Meet People">
        <figcaption class="carousel-caption">
          <h1>Explore Our Records</h1>
          <font size="5"><p>Search for Family Members </p></font>

          <p><a class="btn btn-lg btn-primary" href="/search/" role="button">Start Searching</a></p>
        </figcaption>
      </figure>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span></a>
  </section>
  <!-- /.carousel -->

	<div class="row clearfix">
		<div class="col-md-4 column">
			<center><h2>
				Expanding Our Area
			</h2></center>
			<p>
				We're working on expanding to additional cemeteries.  More details to come soon!
			</p>
            <p>
                If you are interested in adding your graveyard or have feedback on the site please <a href="mailto:zac@theyburied.us?subject=Expansion or Feedback">contact us</a>!
            </p>

		</div>
		<div class="col-md-4 column">
			<center><h2>
				This is Our Prototype
			</h2></center>
			<p>
				This is our proof of concept prototype of theyburied.us.  That means that we have not completed all the features we would like to include in the site and some of the data for our cemetery hasn’t been uploaded.
            </p>
            <p>
                One of the key parts of the site is photos of each grave marker.  Collecting the images for a cemetery of this size is a time consuming process and we are still in the process of completing it.    We have a small section of markers that do have an image for <a href="/marker/6007/">demonstration</a> of what the site will be like when the images are complete.
			</p>
		</div>
		<div class="col-md-4 column">
			<center><h2>
				Supported By
			</h2></center>
			<p>
				This site is developed by Zac Miller and Crystal Lyliston.
			</p>
            <p>
                Crystal was able to work on the site during the summer of 2014 with funding from the <a href="http://www.ung.edu/">University of North Georgia</a>'s Center for Undergraduate Research and Creative Activites <a href="http://ung.edu/undergraduate-research-creative-activities/index.php">(CURCA)</a> FUSE grant program.
            </p>
		</div>
	</div>
{% endblock content %}

cemeteries/templates/cemeteries/markers_detail.html
{% extends 'base.html' %}


{% block title %} Markers {% endblock %}


{% block content %}
  <font size="5" font face="Comic Sans MS">
    <div class="row">
      <div class="col-md-8">
        {% if image %}
          <p><img src="{{ MEDIA_URL }}{{ image.image }}" width=100% height=auto></p>
          <br>
        {% else %}
          <p>No image exists for grave marker {{ marker.markerid }} at this time. </p>
        {% endif %}
      </div>
      <div class="col-md-4">
        <p><b>Family Name:</b> {{ marker.family_name|capfirst }}<br>
          <b>Marker Id:</b><a href="/marker/{{ marker.markerid }}">{{ marker.markerid }}</a><br>
          <b>Marker Condition:</b> {{ marker.condition }}<br>
          <b>Marker Readability:</b> {{ marker.readable }}<br>
          <b>Marker Epitaph:</b> {{ marker.epitaph }}<br>
          <b>Marker Cemetery</b> : {{ marker.cemetery }}</p><br>
        {% for person in people %}
          <a href="/person/{{ person.pk }}">{{ person.full_name }} {{ person.b_year }}-{{ person.d_year }}</a><br>
        {% endfor %}
      </div>
    </div>
  </font>
  <p align="center" style="font-size:25px">
  {% url "cemeteries:symbology" as symbology %}
  {% if back == symbology %}
  <a href="{{ back }}">Return to Symbology</a>
  {% elif 'cemeteries.marker' in back %}
     <a href="{{ back }}">Return to Search</a>
  {% elif '/person/' in back %}
     <a href="{{ back }}">Return to Person</a>
  {% else %}
    {% url 'cemeteries:person_lview' as people%}
   <a href="{{ people }}">Return to Person Index</a>
  {% endif %}
  </p>
<p align="center" style="font-size:25px"><a href="{% url 'cemeteries:markermap' pk=marker.markerid %}">View Marker on Map</a></p>
{% endblock %}

cemeteries/templates/cemeteries/person_detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}{{ person.full_name }} - Person Detail{% endblock %}
{% block content %}
  <font size="5" font face="Comic Sans MS">
    <div class="row">
      <div class="col-md-8">
        {% if image %}
          <p><img src="{{ MEDIA_URL }}{{ image.image }}" width=100% height=auto></p>
          <br>
        {% else %}
          <p>No image exists for {{ person.full_name }} at this time. </p>
        {% endif %}
      </div>
      <div class="col-md-4">
        <p><b>Cemetery:</b> {{ person.markerid.cemetery }}<br>
          <b>Name:</b> {{ person.full_name }}<br>
          <b>Marker Id:</b> <a href="/marker/{{ person.markerid.markerid }}">{{ person.markerid.markerid }}</a><br>
          <b>Gender:</b> {{ person.gender }}<br>
          <b>Veteran:</b> {{ person.veteran }}<br>
          <b>Born:</b> {{ person.a_birth }}<br>
          <b>Died:</b> {{ person.a_death }}<br>
          <b>Epitaph:</b> {{ person.epitaph }}<br>
          <b>Footstone:</b> {{ person.footstone }}<br>
          <b>Footstone Epitaph:</b> {{ person.footstoneI }}<br>
        {% if wwdc %}
          <br><a href="{{ MEDIA_URL }}{{ wwdc.pdf }}"><img src="{% static "cemeteries/pdf.ico" %}" height="24"
                                                                  width="24"> Go to WWI Draft Card</a></p>
        {% endif %}
  </font>
  </div>
  </div>
    <p align="center" style="font-size:25px">
  {% url "cemeteries:people_view" as people %}
  {% if back == people %}
  <a href="{{ back }}">Return to Search by Category</a>
  {% elif '/marker/' in back %}
     <a href="{{ back }}">Return to Marker</a>
  {% elif 'cemeteries.person' in back%}
     <a href="{{ back }}">Return to Search</a>
  {% else %}
  {% url "cemeteries:person_lview" as index%}
   <a href="{{ index }}">Return to Person Index</a>
  {% endif %}
  </p>
    <p align="center" style="font-size:25px"><a href="{% url 'cemeteries:personmap' pk=person.pk %}">View Person on Map</a></p>
{% endblock %}

cemeteries/templates/cemeteries/symbology.html
{% extends 'base.html' %}

{% block title %} Symbology {% endblock %}

{% block content %}
  <font size="5" font face="Comic Sans MS">
    <h1><b>Explore the Symbology</b></h1><br>
    {% for symbology in object_list|dictsort:"symbology" %}
      <div class="row">
        <div class="col-md-3">
          <button class="btn btn-info btn-lg btn-block" data-toggle="collapse"
                  data-target="#{{ symbology|slugify }}">{{ symbology|capfirst }}</button>
        </div>
        <div class="col-md-9">
          <div class="collapse" id="{{ symbology|slugify }}">
           <font color="#00008b"> <a href="{% url 'cemeteries:symbolmap' pk=symbology.pk %}">View Symbology on Map</a> </font><br>
            {% for marker in symbology.markers.all %}
              <a href="{% url 'cemeteries:marker_dview' pk=marker.pk %}">{{ marker.markerid }}</a>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
  </font>
{% endblock %}

