cemeteries/urls.py
from django.conf.urls import patterns, include, url
from .views import MainView, CemeteryListView, CemeteryDetailView, MarkerListView,MarkerDetailView, WWDCView,WWDCMapView
from .views import PersonListView, PersonDetailView,AboutView, SymbologyView, PeopleView, MarkerMapView,PersonMapView, SymbolMapView, IndividualMarkerMapView, IndividualPersonMapView
from .models import Cemetery, Marker, Person, Symbology
#from django.contrib.auth.decorators import login_required



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fuse2014.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', MainView.as_view(), name='main'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^cemeteries/$', CemeteryListView.as_view(model=Cemetery), name='cem_lview'),
    url(r'^cemeteries/(?P<pk>\d+)/$', CemeteryDetailView.as_view(), name='cem_dview'),
    url(r'^marker/$', MarkerListView.as_view(model=Marker), name='marker_lview'),
    url(r'^marker/(?P<pk>\d+)/$', MarkerDetailView.as_view(), name='marker_dview'),
    url(r'^person/$', PersonListView.as_view(model=Person), name='person_lview'),
    url(r'^person/(?P<pk>\d+)/$', PersonDetailView.as_view(), name='person_dview'),
    url(r'^people_search/$', PeopleView.as_view(), name='people_view'),
    url(r'^symbology/$', SymbologyView.as_view(model=Symbology), name='symbology'),
    url(r'^map_marker/$', MarkerMapView.as_view(), name='markermap'),
    url(r'^wwdc/$', WWDCView.as_view(), name='WWDC_view'),
    url(r'^map_person/$', PersonMapView.as_view(), name='personmap'),
    url(r'^map_wwdc/$', WWDCMapView.as_view(), name='WWDC_map'),
    url(r'^symbolmap/(?P<pk>\d+)/$', SymbolMapView.as_view(), name='symbolmap'),
    url(r'^markermap/(?P<pk>\d+)/$', IndividualMarkerMapView.as_view(), name='markermap'),
    url(r'^personmap/(?P<pk>\d+)/$', IndividualPersonMapView.as_view(), name='personmap'),
)

fuse2014/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.http import HttpResponse
from fuse2014.sitemaps import MainSitemap
from cemeteries.models import Person, Cemetery

sitemaps = {
    'mainpage': MainSitemap,
    'people': GenericSitemap({'queryset': Person.objects.all(), }, changefreq='monthly', priority=0.6),
    'cemeteries': GenericSitemap({'queryset': Cemetery.objects.all(), }, changefreq='monthly', priority=0.6),
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fuse2014.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cemeteries.urls', namespace='cemeteries')),
    url(r'^api/v1/', include('cemeteries.api_urls', namespace='cemeteries_api')),
    url(r'^search/', include('haystack.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^sitemap\.xml$',
        'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /api/", content_type="text/plain"))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}


<!DOCTYPE html>

<html>
<head>
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <meta name='viewport' content='initial-scale=1,maximum-scale=22,user-scalable=yes' />
    {% block morehead %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Home</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/about">About</a></li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Explore <b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                        <li><a href="{% url 'cemeteries:cem_lview' %}">Cemeteries</a></li>
                        <li><a href="{% url 'cemeteries:marker_lview' %}">Grave Markers</a></li>
                        <li><a href="{% url 'cemeteries:symbology' %}">Symbology</a></li>
                        <li role="presentation" class="dropdown-header">View People By</li>
                        <li><a href="{% url 'cemeteries:person_lview' %}">Full Name</a></li>
                        <li><a href="{% url 'cemeteries:people_view' %}">Category</a></li>
                        <li><a href="{% url 'cemeteries:WWDC_view' %}">World War I Draftees</a></li>
                      </ul>
                      <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Maps <b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                      <li><a href="{% url 'cemeteries:markermap' %}">Grave Marker Map </a></li>
                      <li><a href="{% url 'cemeteries:personmap' %}">Person Map </a></li>
                      <li><a href="{% url 'cemeteries:WWDC_map' %}">World War I Draftee Map </a></li>
                    </ul>
                    <li><a href="/search">Search</a></li>
                </li>
            </li>
            </ul>


            <!--            <form class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
            -->
{#            <ul class="nav navbar-nav navbar-right">#}
{#                {% if user.username %}#}
{#                    <li><a href="/accounts/logout/">Log Out</a></li>#}
{#                {% else %}#}
{#                    <li><a href="/accounts/login/">Login</a></li>#}
{#                    <li><a href="/accounts/register/">Register</a></li>#}
{#                {% endif %}#}
{##}
{#                {% if user.is_staff %}#}
{#                    <li><a href="/admin/">Admin</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{##}
{#            </li>#}
{#            </ul>#}
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<section class="container">
    <div id="messages">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}


    <div id="wrap">
        <div id="main" class="container clear-top" style="font-weight:bold;  ">
            <p>

            </p>
        </div>
    </div>
    <footer class="footer"></footer>

</section>
<!-- /.container -->
<!-- all js here so page loads faster -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
{% block scriptspace %}{% endblock %}
</body>
</body>
</html>